spring.datasource.url=jdbc:postgresql://localhost:5433/pokemon
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ile pokemonow moze maksymalnie posiadac jeden gracz
pokemon.max-per-player=10

# Jaki procent maksymalnego HP odzyskuje pokemon przy comiesiecznym/co-godzinnym resecie
pokemon.hp-reset.regen-percent=80
